apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackboard
spec:
  selector:
    matchLabels:
      run: hackboard
  replicas: 1
  template:
    metadata:
      labels:
        run: hackboard
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: hackboard-secret
      containers:
      - name: hackboard
        image: gcr.io/mchacks-api/hackboard:1.0.2
        ports:
        # - containerPort: 443
        - containerPort: 8080